= Contributing to _OOA Book_

Welcome potential contributor!  Your participation is gladly received.
This short note explains a few keys to becoming a productive collaborator
on the project.  Authors, reviewers, researchers, translators and other
roles are necessary to the success of the project.

== Issue Tracking
Part of contributing is using the correct issue tracker.  The
https://www.redmine.org/[Redmine] -based bug tracker found at
https://support.onefact.net/[One Fact Support Issue Tracker (Redmine)]
is used to track the development of this book.  Register for a user ID
on this tracker.  Raise and follow issues there.  Each change or addition
to the book will be associated with an issue in this tracker.
////
== Issueを登録する
////

== Small Corrections
Errata and basic clarifications will be accepted if the authors agree that
they improve the content.  You can also open an issue so the team can figure
out how or if the correction needs to be addressed.
////
=== 軽微な修正
誤字脱字修正や基本的な説明の追加を受理する前に、それらが本の内容をよりよくするかどうか合意する必要があります。議論のためのissueをたてて、どのように対処すべきか、そもそも対処すべきなのか話し合ってもかまいません。
////

== Licensing
// ## ライセンス

By opening a pull request (PR) to this repository, you agree to provide
your work under the link:LICENSE.adoc[project license], and you agree
to grant such license of your work, as is required for the purposes of
future print editions, to One Fact, Inc.  Should your changes appear
in a printed edition, you will be included in the
link:book/contributors.adoc[contributors list].
////
このリポジトリへプルリクエストをおこなった場合、[プロジェクトのライセンス](LICENSE.adoc) に同意したものとみなします。
また、あなたの貢献を今後の出版物に用いるとき、xtuml-jpグループ にそのライセンスを付与することにも同意したものとみなします。
あなたが加えた変更が出版物に掲載される場合、[貢献者リスト](book/contributors.adoc) に名前が掲載されます。
////

